# Generated by Django 4.2.6 on 2025-09-22 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(help_text='URL‑friendly identifier (e.g. john-wedding-hall-a).', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seatselection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.table'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='orders.menuitem'),
        ),
        migrations.AlterField(
            model_name='seatselection',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_selections', to='orders.menuitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='party',
            field=models.ForeignKey(blank=True, help_text='Event this order belongs to (optional for legacy data).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.party'),
        ),
        migrations.AddField(
            model_name='table',
            name='party',
            field=models.ForeignKey(blank=True, help_text='Event that this table participates in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='orders.party'),
        ),
        migrations.CreateModel(
            name='PartyMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='If set, this price replaces the MenuItem.price for the party.', max_digits=8, null=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_links', to='orders.menuitem')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='orders.party')),
            ],
            options={
                'ordering': ['party', 'menu_item__name'],
                'unique_together': {('party', 'menu_item')},
            },
        ),
    ]
