# Generated by Django 4.2.6 on 2025-09-30 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_order_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Server that will take orders for this seat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_seats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seat',
            name='label',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
