# Generated by Django 4.2.6 on 2025-10-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_modifier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifier',
            name='name',
            field=models.CharField(default='gen', help_text='Full description of the modifier (e.g. ‘Extra mozzarella cheese’).', max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
