# Generated by Django 4.2.6 on 2025-10-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_modifier_name'),
    ]

    operations = [
    ]
