# Generated by Django 4.2.6 on 2025-10-12 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_delete_all_modifiers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifier',
            name='name',
        ),
    ]
