# Generated by Django 4.2.6 on 2025-10-12 06:50

from django.db import migrations
def delete_all_modifiers(apps, schema_editor):
    Modifier = apps.get_model('orders', 'Modifier')
    # Using .all().delete() respects cascade rules (if any FK points to Modifier)
    Modifier.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_modifier_name'),
    ]

    operations = [
        migrations.RunPython(delete_all_modifiers, reverse_code=migrations.RunPython.noop),
    ]