# Generated by Django 4.2.6 on 2025-10-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_modifier_name'),
        ('orders', '0011_delete_all_modifiers'),
    ]

    operations = [
    ]
