# Generated by Django 4.2.6 on 2025-10-12 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_modifier_name'),
    ]

    operations = [
       
    ]
