# Generated by Django 4.2.6 on 2025-10-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_merge_20251012_0253'),
        ('orders', '0013_remove_modifier_name'),
    ]

    operations = [
    ]
