# Generated by Django 4.2.6 on 2025-10-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_merge_20251012_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifier',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
