# Generated by Django 4.2.6 on 2025-10-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_modifier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifier',
            name='name',
            field=models.CharField(default='gen', max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
