# Generated by Django 4.2.6 on 2025-10-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_modifier_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Temperatures',
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='modifiers',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='orders.modifier'),
        ),
        migrations.AlterField(
            model_name='seatselection',
            name='modifiers',
            field=models.ManyToManyField(blank=True, related_name='selections', to='orders.modifier'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='temperatures',
            field=models.ManyToManyField(blank=True, help_text='Select which temperature / color options are allowed for this dish.', related_name='menu_items', to='orders.temperature'),
        ),
        migrations.AddField(
            model_name='seatselection',
            name='temperatures',
            field=models.ManyToManyField(blank=True, related_name='selections', to='orders.temperature'),
        ),
    ]
